# Generated by Django 5.0.5 on 2024-05-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='sound_grades',
            field=models.ManyToManyField(related_name='sound_grades', to='training.grades', verbose_name='Оценки по звучанию'),
        ),
    ]
