# Generated by Django 5.0.5 on 2024-05-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_training_session_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty_level',
            name='training_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training_mode', verbose_name='Режим обучения'),
        ),
    ]
