# Generated by Django 5.0.5 on 2024-05-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_student_alter_settings_user_alter_statistic_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_mode',
            name='training_session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='training.training_session', verbose_name='Обучающая сессия'),
        ),
    ]
