# Generated by Django 5.0.5 on 2024-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_remove_training_mode_training_session_choice_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty_level',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Сложность'),
        ),
    ]
