# Generated by Django 5.0.5 on 2024-05-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_difficulty_level_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Exercise',
            new_name='exercise',
        ),
    ]
