# Generated by Django 5.0.5 on 2024-05-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_rename_exercise_choice_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty_level',
        ),
        migrations.CreateModel(
            name='Exercise_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название теста')),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.difficulty_level', verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
