# Generated by Django 5.0.5 on 2024-05-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_remove_exercise_difficulty_level_exercise_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.exercise_block', verbose_name='Тест'),
        ),
    ]
