# Generated by Django 5.0.5 on 2024-05-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_exercise_exercise_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Номер в списке'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercise_block', verbose_name='Тест'),
        ),
    ]
