# Generated by Django 5.0.5 on 2024-05-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_exercise_num_alter_exercise_exercise_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correct_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Правильный ответ')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercise', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
