# Generated by Django 5.0.5 on 2024-05-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_remove_exercise_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='audio_task',
            field=models.FileField(default=None, null=True, upload_to='sound', verbose_name='Аудио-задание'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='task',
            field=models.TextField(blank=True, default='Task in audio file', verbose_name='Задание'),
        ),
    ]
