# Generated by Django 5.0.5 on 2024-05-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_exercise_audio_task_alter_exercise_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='task',
            field=models.TextField(blank=True, verbose_name='Задание'),
        ),
    ]
