# Generated by Django 5.0.5 on 2024-05-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_alter_exercise_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='translation_grades',
            new_name='translate_grades',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='task',
            field=models.TextField(blank=True, verbose_name='Задание'),
        ),
    ]
