# Generated by Django 5.0.5 on 2024-05-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_result_processed_alter_statistic_sound_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_block',
            name='is_active_block',
            field=models.BooleanField(default=False, verbose_name='Активный блок'),
        ),
    ]
